import { User, Lead, LeadStatus, LeadType, Product, Quotation, Invoice, Proposal, Sale, SupportTicket } from './types';

export const initialUsers: User[] = [
  {
    id: 'user_admin_1',
    name: 'Alexander Wright',
    email: 'admin@enterprise.io',
    phone: '+91 98765 43210',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_agent_1',
    name: 'Sarah Jenkins',
    email: 'agent@enterprise.io',
    phone: '+91 98765 11223',
    role: 'AGENT',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_agent_2',
    name: 'Devon Patel',
    email: 'devon@enterprise.io',
    phone: '+91 98765 33445',
    role: 'AGENT',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_support_1',
    name: 'Elena Rostova',
    email: 'support@enterprise.io',
    phone: '+91 98765 55667',
    role: 'SUPPORT',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const initialStatuses: LeadStatus[] = [
  { id: 'status_1', name: 'New Lead', color: '#3b82f6' },
  { id: 'status_2', name: 'Contacted', color: '#f59e0b' },
  { id: 'status_3', name: 'Proposal Sent', color: '#8b5cf6' },
  { id: 'status_4', name: 'Negotiation', color: '#ec4899' },
  { id: 'status_5', name: 'Converted / Won', color: '#10b981' },
  { id: 'status_6', name: 'Not Interested', color: '#6b7280' },
];

export const initialTypes: LeadType[] = [
  { id: 'type_1', name: 'Hot Lead 🔥' },
  { id: 'type_2', name: 'Warm Lead ☀️' },
  { id: 'type_3', name: 'Cold Lead ❄️' },
  { id: 'type_4', name: 'Enterprise Key Account 🏢' },
];

export const initialProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Enterprise Cloud CRM (Annual)',
    hsnCode: '998313',
    price: 49999,
    description: 'Full-featured enterprise license for up to 25 agents with SLA support',
    taxRate: 18,
  },
  {
    id: 'prod_2',
    name: 'Omnichannel WhatsApp Business API',
    hsnCode: '998411',
    price: 18500,
    description: 'Meta Verified green tick API gateway with 100k free incoming sessions',
    taxRate: 18,
  },
  {
    id: 'prod_3',
    name: 'Promotional & Transactional SMS Gateway',
    hsnCode: '998412',
    price: 12000,
    description: 'DLT-registered high priority SMPP connection with 99.98% throughput',
    taxRate: 18,
  },
  {
    id: 'prod_4',
    name: 'AI Voice Bot & IVR Automation Suite',
    hsnCode: '998314',
    price: 34000,
    description: 'Neural voice conversational agent with native CRM bi-directional sync',
    taxRate: 18,
  },
];

const now = new Date();
const in10Minutes = new Date(now.getTime() + 10 * 60 * 1000).toISOString();
const pastHour = new Date(now.getTime() - 60 * 60 * 1000).toISOString();
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString();

export const initialLeads: Lead[] = [
  {
    id: 'lead_1',
    name: 'Rajesh Sharma',
    company: 'Apex Logistics Ltd',
    email: 'rajesh.sharma@apexlogistics.in',
    phone: '+91 98200 44551',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Andheri East, Seepz Zone 4',
    source: 'Website Demo Request',
    callbackDate: in10Minutes, // Due for reminder test!
    notes: 'Urgent requirement for WhatsApp API integration and 15 CRM user licenses.',
    statusId: 'status_2',
    status: initialStatuses[1],
    typeId: 'type_1',
    type: initialTypes[0],
    assignedToId: 'user_agent_1',
    assignedTo: initialUsers[1],
    remarks: [
      {
        id: 'rem_1',
        leadId: 'lead_1',
        note: 'Spoke with CTO Rajesh. They have 40 delivery hubs and require real-time dispatch alerts.',
        createdBy: 'Sarah Jenkins',
        createdAt: pastHour,
      },
    ],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead_2',
    name: 'Priya Sundaram',
    company: 'Fintech NeoBank Labs',
    email: 'priya@fintechneobank.com',
    phone: '+91 98450 77123',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: 'Indiranagar 100ft Road',
    source: 'LinkedIn Campaign',
    callbackDate: tomorrow,
    notes: 'Evaluating Enterprise CRM for customer support triage and DLT SMS routing.',
    statusId: 'status_3',
    status: initialStatuses[2],
    typeId: 'type_4',
    type: initialTypes[3],
    assignedToId: 'user_agent_1',
    assignedTo: initialUsers[1],
    remarks: [
      {
        id: 'rem_2',
        leadId: 'lead_2',
        note: 'Sent rate chart proposal. Awaiting budget committee sign-off on Tuesday.',
        createdBy: 'Sarah Jenkins',
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead_3',
    name: 'Amitabh Verma',
    company: 'Zenith Retail Chain',
    email: 'averma@zenithretail.in',
    phone: '+91 99100 23456',
    city: 'New Delhi',
    state: 'Delhi',
    address: 'Connaught Place Outer Circle',
    source: 'Cold Outreach',
    callbackDate: null,
    notes: 'High volume bulk SMS requirements during festive discount season.',
    statusId: 'status_5',
    status: initialStatuses[4],
    typeId: 'type_1',
    type: initialTypes[0],
    assignedToId: 'user_agent_2',
    assignedTo: initialUsers[2],
    remarks: [
      {
        id: 'rem_3',
        leadId: 'lead_3',
        note: 'Quotation approved. Invoice paid via NEFT. Onboarding scheduled.',
        createdBy: 'Devon Patel',
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead_4',
    name: 'Kavita Menon',
    company: 'CarePlus Diagnostics',
    email: 'kavita@careplusdiag.org',
    phone: '+91 97411 99880',
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'HITEC City Phase 2',
    source: 'Google Ads',
    callbackDate: new Date(Date.now() + 2 * 3600000).toISOString(),
    notes: 'Need patient appointment reminder bot with WhatsApp interactive buttons.',
    statusId: 'status_1',
    status: initialStatuses[0],
    typeId: 'type_2',
    type: initialTypes[1],
    assignedToId: 'user_agent_2',
    assignedTo: initialUsers[2],
    remarks: [],
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialQuotations: Quotation[] = [
  {
    id: 'quote_1',
    quotationNumber: 'QT-2026-0001',
    leadId: 'lead_2',
    agentId: 'user_agent_1',
    subject: 'Enterprise Cloud CRM & WhatsApp Gateway Proposal',
    offer: 'Early bird 10% discount on 1st year billing',
    discount: 5000,
    subtotal: 68499,
    gstAmount: 11429.82,
    grandTotal: 74928.82,
    status: 'PENDING',
    validTill: new Date(Date.now() + 15 * 86400000).toISOString(),
    callbackDate: tomorrow,
    termsConditions: '1. 100% advance on license setup.\n2. Standard SLA response within 2 hours.\n3. GST @ 18% extra.',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    items: [
      {
        description: 'Enterprise Cloud CRM (Annual)',
        quantity: 1,
        rate: 49999,
        taxRate: 18,
        taxable: 49999,
        gstAmount: 8999.82,
        total: 58998.82,
      },
      {
        description: 'Omnichannel WhatsApp Business API',
        quantity: 1,
        rate: 18500,
        taxRate: 18,
        taxable: 18500,
        gstAmount: 3330,
        total: 21830,
      },
    ],
    lead: {
      name: 'Priya Sundaram',
      email: 'priya@fintechneobank.com',
      phone: '+91 98450 77123',
      company: 'Fintech NeoBank Labs',
    },
    agent: {
      name: 'Sarah Jenkins',
      email: 'agent@enterprise.io',
    },
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-GST-2026-0001',
    leadId: 'lead_3',
    agentId: 'user_agent_2',
    isGst: true,
    status: 'PAID',
    subtotal: 49999,
    gstAmount: 8999.82,
    grandTotal: 58998.82,
    paymentMode: 'NEFT / Bank Transfer',
    transactionId: 'HDFC260991823901',
    validTill: null,
    callbackDate: null,
    termsConditions: 'Tax invoice generated under Indian GST regulations.',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    items: [
      {
        description: 'Enterprise Cloud CRM (Annual)',
        quantity: 1,
        rate: 49999,
        taxRate: 18,
        taxable: 49999,
        gstAmount: 8999.82,
        total: 58998.82,
      },
    ],
    lead: {
      name: 'Amitabh Verma',
      email: 'averma@zenithretail.in',
      phone: '+91 99100 23456',
      company: 'Zenith Retail Chain',
    },
    agent: {
      name: 'Devon Patel',
      email: 'devon@enterprise.io',
    },
  },
];

export const initialProposals: Proposal[] = [
  {
    id: 'prop_1',
    leadId: 'lead_2',
    agentId: 'user_agent_1',
    title: 'Enterprise Bulk Messaging & Cloud Services Rate Chart',
    offer: 'Zero Onboarding Fee for Annual Commitments',
    discount: '5%',
    message: 'We are pleased to present our tier-based volume pricing for SMS and WhatsApp campaigns.',
    status: 'Delivered',
    proposalType: 'standard',
    includeRateTable: true,
    slabsData: [
      {
        tableName: 'Promotional SMS Slabs (DLT Registered)',
        rows: [
          { slab: '50,000 - 100,000 SMS', rate: 0.18, discount: 0, bonus: '2,500 Bonus Units', taxable: 18000, gst: 3240, total: 21240 },
          { slab: '100,001 - 500,000 SMS', rate: 0.15, discount: 5, bonus: '15,000 Bonus Units', taxable: 71250, gst: 12825, total: 84075 },
          { slab: '500,001 - 1,000,000 SMS', rate: 0.12, discount: 10, bonus: '50,000 Bonus Units', taxable: 108000, gst: 19440, total: 127440 },
        ],
      },
      {
        tableName: 'WhatsApp Business API Notification Slabs',
        rows: [
          { slab: 'Up to 25,000 Sessions', rate: 0.55, discount: 0, bonus: '500 Free Template Approvals', taxable: 13750, gst: 2475, total: 16225 },
          { slab: '25,001 - 100,000 Sessions', rate: 0.45, discount: 5, bonus: '2,500 Free Template Approvals', taxable: 42750, gst: 7695, total: 50445 },
        ],
      },
    ],
    includePackages: true,
    packagesData: [
      { tierName: 'Starter Wallet', investment: 25000, bonusPercent: 5, totalValue: 26250, description: 'Suitable for pilot testing' },
      { tierName: 'Growth Accelerator', investment: 75000, bonusPercent: 12, totalValue: 84000, description: 'Most popular for expanding brands' },
      { tierName: 'Enterprise Mega Tier', investment: 200000, bonusPercent: 20, totalValue: 240000, description: 'Maximum savings with dedicated RM' },
    ],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    lead: {
      name: 'Priya Sundaram',
      email: 'priya@fintechneobank.com',
      phone: '+91 98450 77123',
    },
    agent: {
      name: 'Sarah Jenkins',
      email: 'agent@enterprise.io',
    },
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale_1',
    leadId: 'lead_3',
    agentId: 'user_agent_2',
    saleDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    amount: 58998.82,
    validity: new Date(Date.now() + 365 * 86400000).toISOString(),
    gstNo: '07AAAAA0000A1Z5',
    modeOfPayment: 'NEFT',
    isPrepaid: true,
    transactionId: 'HDFC260991823901',
    targetAudience: 'North India Retail Buyers',
    targetLocation: 'Delhi NCR',
    dltDone: true,
    dltRequired: true,
    remarks: 'Annual Cloud CRM setup completed. Account activated.',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    lead: { name: 'Amitabh Verma', company: 'Zenith Retail Chain', phone: '+91 99100 23456' },
    agent: { name: 'Devon Patel', email: 'devon@enterprise.io' },
  },
];

export const initialTickets: SupportTicket[] = [
  {
    id: 'ticket_1',
    ticketNumber: 'TICK-839210',
    leadId: 'lead_1',
    createdById: 'user_agent_1',
    assignedToId: 'user_support_1',
    subject: 'Webhook callback signature failure on port 443',
    description: 'Client is attempting to receive WhatsApp incoming message callbacks on their Node backend but receiving 401 signature mismatch.',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    lead: {
      name: 'Rajesh Sharma',
      company: 'Apex Logistics Ltd',
      email: 'rajesh.sharma@apexlogistics.in',
      phone: '+91 98200 44551',
    },
    createdBy: { name: 'Sarah Jenkins', email: 'agent@enterprise.io', role: 'AGENT' },
    assignedTo: { name: 'Elena Rostova', email: 'support@enterprise.io', role: 'SUPPORT' },
    messages: [
      {
        id: 'msg_1',
        ticketId: 'ticket_1',
        senderId: 'user_agent_1',
        message: 'Rajesh from Apex Logistics reached out via call. Their dev team needs verified HMAC secret rotation.',
        createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
        sender: { name: 'Sarah Jenkins', role: 'AGENT' },
      },
      {
        id: 'msg_2',
        ticketId: 'ticket_1',
        senderId: 'user_support_1',
        message: 'Checked the sandbox logs. Their header was missing the sha256= prefix. Sent updated node snippet to their engineering lead.',
        createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
        sender: { name: 'Elena Rostova', role: 'SUPPORT' },
      },
    ],
  },
  {
    id: 'ticket_2',
    ticketNumber: 'TICK-471092',
    leadId: 'lead_2',
    createdById: 'user_agent_1',
    assignedToId: 'user_support_1',
    subject: 'DLT Entity ID verification query',
    description: 'Assistance needed in registering promotional SMS header on Vilpower portal.',
    priority: 'MEDIUM',
    status: 'OPEN',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    lead: {
      name: 'Priya Sundaram',
      company: 'Fintech NeoBank Labs',
      email: 'priya@fintechneobank.com',
      phone: '+91 98450 77123',
    },
    createdBy: { name: 'Sarah Jenkins', email: 'agent@enterprise.io', role: 'AGENT' },
    assignedTo: { name: 'Elena Rostova', email: 'support@enterprise.io', role: 'SUPPORT' },
    messages: [
      {
        id: 'msg_3',
        ticketId: 'ticket_2',
        senderId: 'user_agent_1',
        message: 'Attached DLT documentation guidelines and GST registration proof.',
        createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
        sender: { name: 'Sarah Jenkins', role: 'AGENT' },
      },
    ],
  },
];
